const characters = {
  'sly cooper': {
    name: "Sly Cooper",
    species: "Raccoon",
    description: "Sly Cooper is a charismatic and skilled raccoon thief with a deep sense of honor.",
    img: "https://static.wikia.nocookie.net/sly/images/b/be/Sly_Cooper_from_Sly_1.png",
    abilitiesAndSkills: ["Master thief", "Stealth and agility", "Mastery of various gadgets"],
    roles: ["Protagonist", "Leader of the Cooper Gang"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves", "Sly Cooper: Thieves in Time"],
    backstory: "Sly Cooper comes from a long line of master thieves known as the Cooper Clan. He is determined to reclaim his family's stolen legacy.",
    voiceActor: "Kevin Miller",
    quotes: ["You can't out-sneak a sneak thief.", "I'm the best thief in the world!"],
    trivia: "Sly Cooper's trademark color is blue, representing his stealthy nature."
  },
  'bentley': {
    name: "Bentley",
    species: "Turtle",
    description: "Bentley is a brilliant and tech-savvy turtle who serves as the brains of the Cooper Gang.",
    img: "https://static.wikia.nocookie.net/sly/images/7/74/Bentley_from_Sly_3.png",
    abilitiesAndSkills: ["Genius-level intellect", "Hacking and computer expertise", "Wheelchair-bound but uses various gadgets"],
    roles: ["Supporting character", "Hacker"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves", "Sly Cooper: Thieves in Time"],
    backstory: "Bentley is a former child prodigy and has a knack for inventing gadgets to assist the Cooper Gang in their heists.",
    voiceActor: "Matt Olsen",
    quotes: ["I'll hack my way into their mainframe and cripple their operation!", "I'm Bentley, the master of technology!"],
    trivia: "Bentley is confined to a wheelchair due to an accident but compensates with his technological expertise."
  },
  'murray': {
    name: "Murray",
    species: "Hippo",
    description: "Murray is a strong and fearless hippo who serves as the brawn of the Cooper Gang.",
    img: "https://static.wikia.nocookie.net/sly/images/0/0e/The_Murray.png",
    abilitiesAndSkills: ["Superhuman strength", "Hand-to-hand combat", "Expert driving skills"],
    roles: ["Supporting character", "Driver", "Muscle"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves", "Sly Cooper: Thieves in Time"],
    backstory: "Murray is a former competitive van surfer who joined the Cooper Gang to aid his friends and seek justice against the villains.",
    voiceActor: "Chris Murphy",
    quotes: ["I've got the muscle, Sly! Let me use it!", "My fists have been itching for some action!"],
    trivia: "Murray has a passion for van surfing and enjoys driving the team's getaway vehicle."
  },
  'connor cooper': {
    name: "Conner Cooper",
    species: "Raccoon",
    description: "Conner Cooper is the legendary master thief and the father of Sly Cooper.",
    img: "https://static.wikia.nocookie.net/sly/images/a/a2/The_Secret_Police_File_1.png",
    abilitiesAndSkills: ["Exceptional thieving skills", "Mastery of stealth", "Strategic planning"],
    roles: ["Cooper Clan leader", "Mentor to Sly Cooper"],
    appearances: ["Sly Cooper: Thieves in Time"],
    backstory: "Conner Cooper led the Cooper Clan during their prime, protecting the Thievius Raccoonus, and Conner was killed by the Fiendish Five unannounced, leaving behind a legacy for his son Sly to trackdown and steal back.",
    voiceActor: "",
    quotes: ["A true thief always keeps his word.", "Remember, Sly: Family first."],
    trivia: "Conner Cooper's disappearance is a central mystery in the Sly Cooper series, driving the storyline and Sly's quest to find his father."
  },
  'carmelita fox': {
    name: "Inspector Carmelita Fox",
    species: "Fox",
    description: "Carmelita Fox is a determined and skilled law enforcement officer, constantly pursuing Sly Cooper.",
    img: "https://static.wikia.nocookie.net/sly/images/b/b5/Sly3-carmelita1.png",
    abilitiesAndSkills: ["Expert markswoman", "Master of various law enforcement gadgets", "Skilled in hand-to-hand combat"],
    roles: ["Supporting character", "Antagonist-turned-ally"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves", "Sly Cooper: Thieves in Time"],
    backstory: "Carmelita Fox is an officer in Interpol, known for her unwavering pursuit of Sly Cooper, but eventually becomes an ally and works alongside him to bring down mutual enemies.",
    voiceActor: "Ruth Livier",
    quotes: ["I will bring you to justice, Cooper!", "You may have stolen my heart, Cooper, but I won't let you steal anything else!"],
    trivia: "Carmelita Fox is known for her trademark blue police uniform and her constant efforts to apprehend Sly Cooper, despite developing feelings for him over time."
  },
  'raleigh': {
    name: "Raleigh the Frog",
    species: "Frog",
    description: "Raleigh is a skilled engineer and the chief machinist of the Fiendish Five. He is known for his giant mechanical suits and his explosive temper.",
    img: "https://static.wikia.nocookie.net/sly/images/a/a9/Raleigh.png",
    abilitiesAndSkills: ["Engineering", "Mechanics", "Explosives"],
    roles: ["Antagonist", "Leader of the Fiendish Five"],
    appearances: ["Sly Cooper and the Thievius Raccoonus"],
    backstory: "Raleigh was born into a family of engineers and grew up to be a brilliant inventor. He was recruited by the Fiendish Five to help them steal the Thievius Raccoonus.",
    voiceActor: "Kevin Blackton",
    quotes: ["I'm going to crush you, Cooper!", "You're no match for my giant mechanical suit!"],
    trivia: "Raleigh's giant mechanical suit is based on the design of a steam engine.",
  },
  'muggshot': {
    name: "Muggshot",
    species: "Bulldog",
    description: "Muggshot is a ruthless crime lord who is the chief enforcer of the Fiendish Five. He is known for his massive size, his powerful pistols, and his quick temper.",
    img: "https://static.wikia.nocookie.net/sly/images/a/ad/Muggshot_from_Sly_1.png",
    abilitiesAndSkills: ["Gambling", "Weapons", "Leadership"],
    roles: ["Antagonist", "Chief Enforcer of the Fiendish Five"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 3: Honor Among Thieves"],
    backstory: "Muggshot was born into a life of crime and quickly rose through the ranks of the criminal underworld. He was recruited by the Fiendish Five to help them steal the Thievius Raccoonus.",
    voiceActor: "Kevin Blackton",
    quotes: ["You're going down, Cooper!", "I'm the best there is at what I do, and what I do isn't pretty!"],
    trivia: "Muggshot's name is a reference to the mugshot, a photograph taken of a criminal after they have been arrested.",
  },
  'mz. ruby': {
    name: "Mz. Ruby",
    species: "Alligator",
    description: "Mz. Ruby is an evil voodoo priestess who is the chief mystic of the Fiendish Five. She is known for her dark magic and her ability to summon the dead.",
    img: "https://static.wikia.nocookie.net/sly/images/d/d3/Mz._Ruby.png",
    abilitiesAndSkills: ["Magic", "Summoning", "Necromancy"],
    roles: ["Antagonist", "Chief Mystic of the Fiendish Five"],
    appearances: ["Sly Cooper and the Thievius Raccoonus"],
    backstory: "Mz. Ruby was born into a family of voodoo practitioners and grew up to be a powerful sorceress. She was recruited by the Fiendish Five to help them steal the Thievius Raccoonus.",
    voiceActor: "Presciliana Esparolini",
    quotes: ["You'll never defeat me, Cooper!", "I'll summon the dead to destroy you!"],
    trivia: "Mz. Ruby's name is a reference to the ruby, a precious stone that is often associated with magic and power.",
  },
  'chumley': {
    name: "Chumley",
    species: "Alligator Snapping Turtle",
    description: "Chumley is a large and powerful alligator snapping turtle who serves as one of Mz. Ruby's servants. He is known for his sharp teeth and his powerful bite.",
    img: "https://static.wikia.nocookie.net/sly/images/b/b2/Fire_Turtle_Guard.png",
    abilitiesAndSkills: ["Strength", "Bite", "Swimming"],
    roles: ["Antagonist", "Servant of Mz. Ruby"],
    appearances: ["Sly Cooper and the Thievius Raccoonus"],
    backstory: "Chumley was born in the swamp and grew up to be a fearsome predator. He was recruited by Mz. Ruby to help her steal the Thievius Raccoonus.",
    voiceActor: '',
    quotes: '',
    trivia: "Chumley's name is a reference to the chum, a type of bait used to attract fish.",
  },
  'panda king': {
    name: "Panda King",
    species: "Panda",
    description: "The Panda King is a skilled pyrotechnician who resides in the Kunlun Mountains of western China. He is known for his explosive fireworks and his fiery temper.",
    img: "https://static.wikia.nocookie.net/sly/images/9/90/Panda_King_from_Sly_1.png",
    abilitiesAndSkills: ["Fireworks", "Explosives", "Martial Arts"],
    roles: ["Antagonist", "Master Pyrotechnician"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 3: Honor Among Thieves"],
    backstory: "The Panda King was born into a family of fireworks makers and grew up to be a master pyrotechnician. He was recruited by the Fiendish Five to help them steal the Thievius Raccoonus.",
    voiceActor: "Jim Cummings",
    quotes: ["You'll never defeat me, Cooper!", "I'll blow you to smithereens!"],
    trivia: "The Panda King's name is a reference to the Chinese legend of the panda, a creature that is said to be a master of fire."
  },
  'clockwerk': {
    name: "Clockwerk",
    species: "Eurasian Eagle-Owl",
    description: "Clockwerk is a mechanical owl who is the main antagonist of the Sly Cooper series. He is obsessed with revenge on the Cooper Clan, and he will stop at nothing to destroy them.",
    img: "https://static.wikia.nocookie.net/sly/images/c/c7/MetalClockwerk.png",
    abilitiesAndSkills: ["Flight", "Strength", "Technological Expertise"],
    roles: ["Antagonist", "Leader of the Fiendish Five"],
    appearances: ["Sly Cooper and the Thievius Raccoonus", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves"],
    backstory: "Clockwerk was once a mortal owl who was obsessed with the Cooper Clan. He was eventually killed by Sly Cooper's ancestor, but he was rebuilt as a mechanical owl. He has been hunting the Cooper Clan ever since.",
    voiceActor: "Kevin Blackton",
    quotes: ["You Coopers have always been a thorn in my side!", "I will destroy you all!"],
    trivia: "Clockwerk's name is a reference to the cuckoo clock, a type of clock that is powered by a spring.",
  },
  'unknown': {
    name: "",
    species: "",
    description: "",
    img: "",
    abilitiesAndSkills: [],
    roles: [],
    appearances: [],
    backstory: "",
    voiceActor: "",
    quotes: [],
    trivia: "",
  }
  // keep unknown (default) last
}
module.exports = characters